---
title: "longitudinal water quality data analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{longitudinal water quality data analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bayTools)

# plotting libraries
library(ggplot2)

```

Retrieve WQM site data with NHD-comid data attached
```{r}

site_data <- bt_get_site_data()

```

Retrieve WQM field and lab data, query in weather data from Openmeteo API
```{r}

wqm_data <- bt_get_wqm_data()

```
Let's plot a couple elements longitudinally!

```{r}

# Let's use only data from the September 2023 PRKN longitudinal samples
prkn_lss <- wqm_data %>%
  filter(
    survey_type == 'synoptic',
    Date == "230920" | Date == "230927",
    !grepl('dup', sample_name),
  ) %>%
  mutate(
    event = ifelse(Date == "230920", "before", "after"),
    )

prkn_lss_nhd <- prkn_lss %>% 
  left_join(site_data, by = 'site_code') 

colnames(prkn_lss_nhd)

# LEt's pull in data from the Potomac Riverkeeper, downloaded from the CMC
cmc_prkn <- read.csv('cmc_prkn_202309XX_munged.csv') %>%
  mutate(
    date = lubridate::date(date)
  )

prkn_lss_nhd <- prkn_lss_nhd %>%
  left_join(cmc_prkn, by = c('site_code', 'date'))

prkn_lss_nhd <- prkn_lss_nhd %>%
  mutate(
    `Cr mg/L` = case_when(`Cr mg/L` < 0 ~ 0, .default = `Cr mg/L`),
    `U mg/L` = case_when(`U mg/L` < 0 ~ 0, .default = `U mg/L`)
  ) %>%
  tidyr::unnest(S_275_295, S_350_400, `Slope Ratio`)
  

head(prkn_lss_nhd$pathlength)
head(prkn_lss_nhd$`K mg/L`)

elements <- c(
              ## "Sr mg/L", "S mg/L", 
              ## "Mg mg/L", "Ca mg/L", 
              "Na mg/L", "K mg/L",
              ## "Cr mg/L", "K mg/L",
              ## "Zn mg/L", "Ni mg/L",
              "U mg/L", #"Cu mg/L",
              ## "Na mg/L", "K mg/L", 
              ## "a254", # "BIX",
              "ecoli",
              ## "daily_temperature_2m_mean", #"Al mg/L",
              ## "Slope Ratio", "P/H",
              "S_275_295",
              "water_temp"
              )


margin_cm <- c(rep(as.character(length(elements)*2), 4), "cm")
rm(element_plots)

element_plots <- lapply(elements, 
                        function(key){
                            gg.prkn_lss <- ggplot(prkn_lss_nhd) +
                             geom_point(
                               aes(x = pathlength, y = get(key), col = event, 
                                   text = paste("site:", site_code)),
                               size = 3,
                               ## position = position_jitter(w = 0.01, h = 0.01)
                               ) +
                                scale_x_reverse() +
                                ggsci::scale_color_npg() +
                                xlab("River Miles Site to Potomac River Outlet (NHD)") +
                                ylab(key) +
                                theme_minimal() +
                                theme(
                                  text = element_text(size = 18),
                                  plot.margin = margin(margin_cm)
                                  ) # +
                                # ggtitle(paste('', key))
                            
                            gg.prkn_lss
                          }
                        )

rm(allplots)
allplots <- ggpubr::ggarrange(
                      plotlist= element_plots,
                      ncol = 2, # round(length(elements)/4), 
                      nrow = 3, #round(length(elements)/2),
                      common.legend=TRUE
                      )

ggpubr::annotate_figure(allplots, 
                top = ggpubr::text_grob("PRKN September 2023, UMD Biogeochemical Analysis\n Before and After Drought-breaking Tropical Storm (UNOFFICIAL AND un-QAQCd DATA, not suitable for any use or dissemination)", 
                color = "black", 
                face = "bold", 
                size = 18))

# explore interactively
plotly::ggplotly(element_plots[[2]])

plotly::ggplotly(element_plots[[5]])
```
