---
title: "prkn"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{prkn}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bayTools)
library(dplyr)
library(googlesheets4)
library(ggplot2)
library(corrplot)
library(GGally)

cmc.prkn <- read.csv('data/PRKN_2023_plus.csv')

head(cmc.prkn)

cmc.prkn.f <- cmc.prkn %>%
  mutate(
    site_code = stringr::str_replace(
                           stringr::str_extract(cmc.prkn$StationName, '([^-]+)(?:-)[0-9]{1,2}'),
                           " |-", ""),
    datetime = format(strptime(paste0(Date, Time), "%m/%d/%Y"), "%Y-%m-%d %H:%M:%S"),
    date = lubridate::date(datetime),
    air_temp = Air.temperature..AT.1.,
    latitude = Latitude,
    longitude = Longitude,
    ecoli = Bacteria..E.Coli...ECOLI.4.,
    pH = pH..PH.3.,
    turbidity = Water.Clarity..WC.6.,
    water_temp = Water.temperature..WT.1.
  ) %>%
  select(
    site_code,
    date,
    time = Time,
    datetime,
    air_temp,
    water_temp,
    pH,
    ecoli,
    turbidity,
    latitude,
    longitude
  )


head(cmc.prkn.f)

## write.csv(cmc.prkn.f, 'cmc_prkn_202309XX_munged.csv')

umd.lab <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/17CMguyAioEv3_qEkUUXe67UbBmJ6ACnNxCKu3W2kmx0/edit#gid=0",
                                     sheet = "data")

head(umd.lab)

wq.pr <- umd.lab %>%
  mutate(
    date = format(strptime(Date, "%y%m%d"), "%m/%d/%Y"),
  ) %>%
  rename(
    time = Time,
    site_code = Site
  ) %>%
  left_join(cmc.prkn.f, by = c('site_code', 'date'))

head(wq.pr)

colnames(wq.pr)

wq.pr.f <- wq.pr %>%
  filter(!is.na(ecoli),
         !is.na(`Fe mg/L`),
         !is.infinite(ecoli),
         !is.infinite(`Fe mg/L`),
         ) %>%
  mutate(
    ecoli_ln = log(ecoli)
  )

ggplot(wq.pr.f) +
  geom_point(aes(x = `Fe mg/L`,
                 y = ecoli,
                 col = date))

# prepare numeric-only df's for all, before, and after data
wq.pr.corr.df <- wq.pr.f[ , colSums(is.na(wq.pr.f)) == 0] %>%
  tidyr::unnest(S_275_295, S_350_400, `Slope Ratio`) %>%
  select(where(is.numeric),
         -`G#`)

wq.pr.corr.before.df <- wq.pr.f[ , colSums(is.na(wq.pr.f)) == 0] %>%
  tidyr::unnest(S_275_295, S_350_400, `Slope Ratio`) %>%
  filter(date == "09/20/2023") %>%
  select(where(is.numeric),
         -`G#`)


wq.pr.corr.after.df <- wq.pr.f[ , colSums(is.na(wq.pr.f)) == 0] %>%
  tidyr::unnest(S_275_295, S_350_400, `Slope Ratio`) %>%
  filter(date == "09/27/2023") %>%
  select(where(is.numeric),
         -`G#`)

# calculate correlation matrix
wq.pr.corr <- cor(wq.pr.corr.df)

wq.pr.corr.before <- wq.pr.corr.before.df %>%
  cor()

wq.pr.corr.after <- wq.pr.corr.after.df %>%
  cor()


# plot all, before, after
testRes = cor.mtest(wq.pr.corr.df, conf.level = 0.95)
wq.pr.corrplot <- corrplot(wq.pr.corr,
         title = "\nSeptember PRKN, Before and After Storm",
         p.mat = testRes$p,
         method = 'color',
         diag = FALSE,
         type = 'upper',
         sig.level = c(0.001, 0.01, 0.05),
         pch.cex = 0.9,
         insig = 'label_sig',
         pch.col = 'grey20',
         order = 'AOE')


testRes.before = cor.mtest(wq.pr.corr.before.df, conf.level = 0.95)
wq.pr.corrplot.before <- corrplot(wq.pr.corr.before,
         title = "\nSeptember PRKN, Before Storm",
         p.mat = testRes.before$p,
         method = 'color',
         diag = FALSE,
         type = 'upper',
         sig.level = c(0.001, 0.01, 0.05),
         pch.cex = 0.9,
         insig = 'label_sig',
         pch.col = 'grey20',
         order = 'AOE')


testRes.after = cor.mtest(wq.pr.corr.after.df, conf.level = 0.95)
wq.pr.corrplot.after <- corrplot(wq.pr.corr.after,
         title = "\nSeptember PRKN, After Storm",
         p.mat = testRes.after$p,
         method = 'color',
         diag = FALSE,
         type = 'upper',
         sig.level = c(0.001, 0.01, 0.05, 0.1),
         pch.cex = 0.9,
         insig = 'label_sig',
         pch.col = 'grey20',
         order = 'AOE')


```

Now, it might be interesting to make a pair plot to look at the regressions between variables

```{r}

# Let's revisit - which relationships were singificant?
# all, before, after
testRes = cor.mtest(wq.pr.corr.df, conf.level = 0.95)
wq.pr.corrplot <- corrplot(wq.pr.corr,
         title = "\nSeptember PRKN, Before and After Storm",
         p.mat = testRes$p,
         method = 'color',
         diag = FALSE,
         type = 'upper',
         sig.level = c(0.001, 0.01, 0.05),
         pch.cex = 0.9,
         insig = 'blank',
         pch.col = 'grey20',
         order = 'AOE')


```

Seems like some of the most singificant variables (edited to some degree for ions of relatively known activity)

```{r}

element_cols <- c(
  "longitude",
  "water_temp",
  "turbidity",
  "ecoli",
  "ecoli_ln",
  "pH",
  "a254",
  "S_275_295",
  "Slope Ratio",
  "BIX",
  "HIX",
  "P/H",
  "Humic-like",
  "Al mg/L",
  "Ca mg/L",
  "B mg/L",
  "Fe mg/L",
  "K mg/L",
  "Mg mg/L",
  "Na mg/L",
  "S mg/L",
  "Sr mg/L",
  "Cu mg/L",
  "Be mg/L",
  "Ag mg/L",
  "U mg/L",
  "Zn mg/L",
  "P mg/L"
)

names.use <- names(wq.pr.corr.df)[(names(wq.pr.corr.df) %in% element_cols)]
wq.pr.pair.df <- wq.pr.corr.df[, names.use]


names.use <- names(wq.pr.corr.before.df)[(names(wq.pr.corr.before.df) %in% element_cols)]
wq.pr.pair.df <- wq.pr.corr.before.df[, names.use]


names.use <- names(wq.pr.corr.after.df)[(names(wq.pr.corr.after.df) %in% element_cols)]
wq.pr.pair.df <- wq.pr.corr.after.df[, names.use]

```

```{r}


GGally::ggpairs(data = wq.pr.pair.df,
        ## columns = c('column name 1', 'column name 2', 'column name 3'),
        title = 'Pairs Plot')

element.gg <- ggplot(wq.pr.pair.df, aes(x = ecoli_ln, y = `S_275_295` #,
                                        ## col = `Humic-like`
                                        )) +
                  geom_point(
                      ## aes(x = `S mg/L`, y = `Sr mg/L`, col = `Humic-like`)
                  ) +
  ## scale_x_log10() +
  ## scale_y_log10() +
  theme_minimal() +
  ggpmisc::stat_poly_line() +
  ggpmisc::stat_poly_eq(ggpmisc::use_label(c("eq", "R2")), size = 10, label.x = 0.8) +
  ggtitle(paste('ecoli (ln of MPU) vs Organic Matter S_275_295, Potomac River Septemeber 2023, Before Storm'),
          subtitle = paste("Before and After Tropical Strom, Colored by Humic-like OM")) +
  ## viridis::scale_color_viridis() +
  theme_minimal() +
  theme(
    text = element_text(size = 26)
  )
  

plotly::ggplotly(element.gg)

```
